pipeline {
    agent any
    environment {
        JAVA_HOME = 'C:\\Program Files\\jdk-21.0.6'
        PATH = "${JAVA_HOME}\\bin;${env.PATH}"
    }
    stages {
        stage('Build') {
            steps {
                bat 'mvn clean install'
            }
        }
    }
}
